### ISSUE TITLE
double input

### ISSUE THREAD

**Issue by vash3d** [raphaelyancey/pyKY040#1]
Hi, I have an issue using this useful library.
I get double input either by rotating as well as pressing the switch. (using it on a raspberry pi 3 b+)

I mean, when rotating by 1, I get
```
The scale position is 1
The scale position is 2

```
then

```
The scale position is 3
The scale position is 4

```
But I can bear with that for what I have to use it.

Major problem are with the switch. When pressing I get
```
Button pressed
Button pressed
```
And I can't use it like this.

**Comment by raphaelyancey** [comment]
Hi @vash3d, thanks for the feedback.

Try increasing the [`polling_interval`](https://github.com/raphaelyancey/pyKY040#encoderclkx-dty-swz) keyword argument.

```python
encoder = Encoder(CLK=23, DT=24, SW=25, polling_interval=5)
```

For the switch, there is also the [`sw_debounce_time`](https://github.com/raphaelyancey/pyKY040#encodersetup) keyword argument for the `setup()` method. In the example below it will only count one switch pressing every 300ms, even if it detects more. Try and adapt to your use case.

```python
encoder.setup(..., sw_debounce_time=300)
```

Tell me if it solved your problem :)

**Comment by vash3d** [comment]
Thanks for the fast replay.
Tried both options with various values but I get the same issues or even worst when rotating (3 or 4 values increase instead of 2) and always the same double input for the switch.

**Comment by raphaelyancey** [comment]
Can you post your code so I can look at it ?

**Comment by vash3d** [comment]
Sure but it's just your code from the documentation.

```
from pyky040 import pyky040
import threading


def my_callback(scale_position):
    print('The scale position is {}'.format(scale_position))


def btn_callback():
    print("Button pressed")


dimmer = pyky040.Encoder(CLK=27, DT=22, SW=17)
dimmer.setup(scale_min=0, scale_max=100, step=1, sw_debounce_time=100, chg_callback=my_callback, sw_callback=btn_callback)
dimmer_thread = threading.Thread(target=dimmer.watch)

dimmer_thread.start()
dimmer.watch()
```

As I said the multiple value when rotating is not a big issue. The real problem is when pressing the switch. I've tried different value for debounce time (from 1 to 1000) but it affects only the time between the presses of the switch. The sw_callback function is always called two times.

**Comment by vash3d** [comment]
Looking at your code...
could it be something related to using `if GPIO.input(self.sw) == GPIO.LOW:` to get the push of the button?
Maybe using event detection?
I've made a test (to check if it was a faulty hardware) and with GPIO.RISING or GPIO.FALLING  the  callback function is called just one time (except for some bouncing issue sometime).
I'm just making a guess... I'm really new to python and all this stuff.

Here my simple testing code:

```
import RPi.GPIO as GPIO


def button_callback(channel):
    print("Button pressed")


GPIO.setmode(GPIO.BCM)
GPIO.setup(17, GPIO.IN, pull_up_down=GPIO.PUD_UP)

GPIO.add_event_detect(17, GPIO.RISING, callback=button_callback)


message = input("Press enter to quit\n\n")
GPIO.cleanup()
```

**Comment by raphaelyancey** [comment]
@vash3d Any update on this issue? I can't test it because I don't have spare encoders right now.

I suggest you clone the python module and add it to the root of your project. Then `import pyky040` will import the local module instead of the `pip`-installed one. From there the debug will be easier, and I'd add a few `logger.info()` here and there to locate the problem more precisely.

Try to know why the `polling_interval` is not taken into account for example, by adding `logger.info(self.polling_interval)` after https://github.com/raphaelyancey/pyKY040/blob/master/pyky040/pyky040.py#L46.

You could also add the same line after https://github.com/raphaelyancey/pyKY040/blob/master/pyky040/pyky040.py#L132

**Comment by vash3d** [comment]
Hi @raphaelyancey , sorry for the late reply.
I've no update on this issue, but inspired by your work, I've taken a different approach and wrote down [my own library](https://github.com/vash3d/pigpio_encoder).
It's still an alpha release but it's working fine for me. I've used the pigpio library instead of the rpi.gpio cause it's seems a lot faster to me.

**Comment by raphaelyancey** [comment]
Nice, I'll look into it! Glad to know it's now working for you. I didn't know `pigpio` so I'll test it as soon as I can setup my testing rig back.

**Comment by SebDominguez** [comment]
Having a similar same issue:
`inc_callback`, `dec_callback`& `chg_callback` get called multiple time for each "steps" of my rotary encoder. `sw_callback` is called once as expected. I tried to change the polling_interval, but this seems to make things worst as if I keep turning the encoder clockwise I'll get the counterclockwise callback executed.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/52816569/70073357-000b4500-15f9-11ea-81bb-da5b172afc02.gif)


Adding `logger.info(self.polling_interval)` on `pyky040.py` at line 47 and 133 give me the following output:`INFO:root:5`

Maybe this is due to the cheap construction of the rotary encoder module? I'm using those one (I thing you are using the same one)

![iu-1](https://user-images.githubusercontent.com/52816569/70072436-495a9500-15f7-11ea-9bc5-22bef42c9145.jpeg)


With the threaded example the callback get called only twice

![2](https://user-images.githubusercontent.com/52816569/70074451-03073500-15fb-11ea-843f-49d629d1562e.gif)

this is the code I run

```python

# Import the module and threading
from pyky040 import pyky040
import threading
import time

# Define your callback
def up_callback(scale_position):
    print("up")

def down_callback(scale_position):
    print("down")

def pressed_callback():
    print("pressed")

# Init the encoder pins
encoder = pyky040.Encoder(CLK=5, DT=6, SW=13, polling_interval=5)

# Setup the options and callbacks (see documentation)
encoder.setup(scale_min=0, scale_max=100, step=1, inc_callback=up_callback, dec_callback=down_callback, sw_callback=pressed_callback)

# Create the thread
my_thread = threading.Thread(target=encoder.watch)

my_thread.daemon=True

# Launch the thread
my_thread.start()

# Do other stuff
print('Other stuff...')
while True:
    print('Looped stuff...')
    time.sleep(10)
# ... this is also where you can setup other encoders!


```
 
---

Well I just received another rotary encoder (PEC16-4220F-S0024) and I still have this issue
